### ISSUE TITLE
Update the Questions app for the SDK version 0.99 f7

### ISSUE THREAD

**Issue by furippa** [nikilark/flipper_questions#3] opened 2024-03-05 04:59 UTC
Hello!

Your Questions app version `1.0` fails to build with the SDK version `0.99.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/655329330d3083c7243b5256/page)

Flipper Team

**Comment by nikilark** [comment] 2024-03-27 09:35
Duplicate of https://github.com/nikilark/flipper_questions/issues/4

**Closed as completed by nikilark** 2024-03-27 09:35 UTC
